version: "4.29.0"

services:
  postgres:
    container_name: cursos_list_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cursos_list
